<?php

namespace Container1dav6Iu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_87uERhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.87uE_rh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.87uE_rh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'purchaseRepository' => ['privates', 'App\\Repository\\PurchaseRepository', 'getPurchaseRepositoryService', true],
            'session' => ['services', 'session', 'getSessionService', false],
        ], [
            'purchaseRepository' => 'App\\Repository\\PurchaseRepository',
            'session' => '?',
        ]);
    }
}
