<?php

namespace Container1dav6Iu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.80nwlvV.App\Entity\Product' shared service.
     *
     * @return \App\Entity\Product
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.80nwlvV": it references class "App\\Entity\\Product" but no such service exists.');
    }
}
