<?php

namespace ContainerY5r4BhZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O_4jVwyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o.4jVwy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o.4jVwy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::addItemToCart' => ['privates', '.service_locator.80nwlvV', 'get_ServiceLocator_80nwlvVService', true],
            'App\\Controller\\CartController::removeItemToCart' => ['privates', '.service_locator.SkKsEeW', 'get_ServiceLocator_SkKsEeWService', true],
            'App\\Controller\\CartController::shoppingCart' => ['privates', '.service_locator.OWBJK42', 'get_ServiceLocator_OWBJK42Service', true],
            'App\\Controller\\CheckoutController::checkout' => ['privates', '.service_locator.W0r5Q6B', 'get_ServiceLocator_W0r5Q6BService', true],
            'App\\Controller\\CheckoutController::confirmation' => ['privates', '.service_locator.87uE_rh', 'get_ServiceLocator_87uERhService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.Zpl.nrE', 'get_ServiceLocator_Zpl_NrEService', true],
            'App\\Controller\\ProductController::showProduct' => ['privates', '.service_locator.Ze8.f9W', 'get_ServiceLocator_Ze8_F9WService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.ngMwSyi', 'get_ServiceLocator_NgMwSyiService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CartController:addItemToCart' => ['privates', '.service_locator.80nwlvV', 'get_ServiceLocator_80nwlvVService', true],
            'App\\Controller\\CartController:removeItemToCart' => ['privates', '.service_locator.SkKsEeW', 'get_ServiceLocator_SkKsEeWService', true],
            'App\\Controller\\CartController:shoppingCart' => ['privates', '.service_locator.OWBJK42', 'get_ServiceLocator_OWBJK42Service', true],
            'App\\Controller\\CheckoutController:checkout' => ['privates', '.service_locator.W0r5Q6B', 'get_ServiceLocator_W0r5Q6BService', true],
            'App\\Controller\\CheckoutController:confirmation' => ['privates', '.service_locator.87uE_rh', 'get_ServiceLocator_87uERhService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.Zpl.nrE', 'get_ServiceLocator_Zpl_NrEService', true],
            'App\\Controller\\ProductController:showProduct' => ['privates', '.service_locator.Ze8.f9W', 'get_ServiceLocator_Ze8_F9WService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.ngMwSyi', 'get_ServiceLocator_NgMwSyiService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CartController::addItemToCart' => '?',
            'App\\Controller\\CartController::removeItemToCart' => '?',
            'App\\Controller\\CartController::shoppingCart' => '?',
            'App\\Controller\\CheckoutController::checkout' => '?',
            'App\\Controller\\CheckoutController::confirmation' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::showProduct' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CartController:addItemToCart' => '?',
            'App\\Controller\\CartController:removeItemToCart' => '?',
            'App\\Controller\\CartController:shoppingCart' => '?',
            'App\\Controller\\CheckoutController:checkout' => '?',
            'App\\Controller\\CheckoutController:confirmation' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:showProduct' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
