<?php

namespace ContainerY5r4BhZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ze8_F9WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ze8.f9W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ze8.f9W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'product' => ['privates', '.errored..service_locator.Ze8.f9W.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.Ze8.f9W": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
