<?php

namespace ContainerCpr3D6D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WTaMKdUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wTaMKdU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wTaMKdU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartStorage' => ['privates', 'App\\Service\\CartStorage', 'getCartStorageService', false],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'product' => ['privates', '.errored..service_locator.wTaMKdU.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.wTaMKdU": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'cartStorage' => 'App\\Service\\CartStorage',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
