<?php

namespace ContainerCpr3D6D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KgtdDgAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KgtdDgA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KgtdDgA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::addItemToCart' => ['privates', '.service_locator.wTaMKdU', 'get_ServiceLocator_WTaMKdUService', true],
            'App\\Controller\\CartController::removeItemToCart' => ['privates', '.service_locator.quvDhFe', 'get_ServiceLocator_QuvDhFeService', true],
            'App\\Controller\\CartController::shoppingCart' => ['privates', '.service_locator.CqVu78O', 'get_ServiceLocator_CqVu78OService', true],
            'App\\Controller\\CheckoutController::checkout' => ['privates', '.service_locator.W515qdl', 'get_ServiceLocator_W515qdlService', true],
            'App\\Controller\\CheckoutController::confirmation' => ['privates', '.service_locator.rzdUZWG', 'get_ServiceLocator_RzdUZWGService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.sykwclQ', 'get_ServiceLocator_SykwclQService', true],
            'App\\Controller\\ProductController::showProduct' => ['privates', '.service_locator.IvJHccu', 'get_ServiceLocator_IvJHccuService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YT8XVZ7', 'get_ServiceLocator_YT8XVZ7Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CartController:addItemToCart' => ['privates', '.service_locator.wTaMKdU', 'get_ServiceLocator_WTaMKdUService', true],
            'App\\Controller\\CartController:removeItemToCart' => ['privates', '.service_locator.quvDhFe', 'get_ServiceLocator_QuvDhFeService', true],
            'App\\Controller\\CartController:shoppingCart' => ['privates', '.service_locator.CqVu78O', 'get_ServiceLocator_CqVu78OService', true],
            'App\\Controller\\CheckoutController:checkout' => ['privates', '.service_locator.W515qdl', 'get_ServiceLocator_W515qdlService', true],
            'App\\Controller\\CheckoutController:confirmation' => ['privates', '.service_locator.rzdUZWG', 'get_ServiceLocator_RzdUZWGService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.sykwclQ', 'get_ServiceLocator_SykwclQService', true],
            'App\\Controller\\ProductController:showProduct' => ['privates', '.service_locator.IvJHccu', 'get_ServiceLocator_IvJHccuService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YT8XVZ7', 'get_ServiceLocator_YT8XVZ7Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CartController::addItemToCart' => '?',
            'App\\Controller\\CartController::removeItemToCart' => '?',
            'App\\Controller\\CartController::shoppingCart' => '?',
            'App\\Controller\\CheckoutController::checkout' => '?',
            'App\\Controller\\CheckoutController::confirmation' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::showProduct' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CartController:addItemToCart' => '?',
            'App\\Controller\\CartController:removeItemToCart' => '?',
            'App\\Controller\\CartController:shoppingCart' => '?',
            'App\\Controller\\CheckoutController:checkout' => '?',
            'App\\Controller\\CheckoutController:confirmation' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:showProduct' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
