<?php

namespace ContainerCpr3D6D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddItemToCartFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AddItemToCartFormType' shared autowired service.
     *
     * @return \App\Form\AddItemToCartFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AddItemToCartFormType.php';

        return $container->privates['App\\Form\\AddItemToCartFormType'] = new \App\Form\AddItemToCartFormType(($container->services['router'] ?? $container->getRouterService()));
    }
}
