<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCpr3D6D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCpr3D6D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCpr3D6D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCpr3D6D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCpr3D6D\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cpr3D6D',
    'container.build_id' => 'ebb4d899',
    'container.build_time' => 1666594979,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCpr3D6D');
