<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxlCuGI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxlCuGI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAxlCuGI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAxlCuGI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAxlCuGI\App_KernelDevDebugContainer([
    'container.build_hash' => 'AxlCuGI',
    'container.build_id' => '3f6e78f2',
    'container.build_time' => 1667402561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxlCuGI');
