<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1dav6Iu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1dav6Iu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1dav6Iu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1dav6Iu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1dav6Iu\App_KernelDevDebugContainer([
    'container.build_hash' => '1dav6Iu',
    'container.build_id' => 'c4893795',
    'container.build_time' => 1666609084,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1dav6Iu');
